In [2]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib
import numpy as np
import pandas as pd

In [14]:
iris = load_iris()
X, y = iris['data'], iris['target']
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [18]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [23]:
list(zip(iris.data,iris.target))

[(array([5.1, 3.5, 1.4, 0.2]), 0),
 (array([4.9, 3. , 1.4, 0.2]), 0),
 (array([4.7, 3.2, 1.3, 0.2]), 0),
 (array([4.6, 3.1, 1.5, 0.2]), 0),
 (array([5. , 3.6, 1.4, 0.2]), 0),
 (array([5.4, 3.9, 1.7, 0.4]), 0),
 (array([4.6, 3.4, 1.4, 0.3]), 0),
 (array([5. , 3.4, 1.5, 0.2]), 0),
 (array([4.4, 2.9, 1.4, 0.2]), 0),
 (array([4.9, 3.1, 1.5, 0.1]), 0),
 (array([5.4, 3.7, 1.5, 0.2]), 0),
 (array([4.8, 3.4, 1.6, 0.2]), 0),
 (array([4.8, 3. , 1.4, 0.1]), 0),
 (array([4.3, 3. , 1.1, 0.1]), 0),
 (array([5.8, 4. , 1.2, 0.2]), 0),
 (array([5.7, 4.4, 1.5, 0.4]), 0),
 (array([5.4, 3.9, 1.3, 0.4]), 0),
 (array([5.1, 3.5, 1.4, 0.3]), 0),
 (array([5.7, 3.8, 1.7, 0.3]), 0),
 (array([5.1, 3.8, 1.5, 0.3]), 0),
 (array([5.4, 3.4, 1.7, 0.2]), 0),
 (array([5.1, 3.7, 1.5, 0.4]), 0),
 (array([4.6, 3.6, 1. , 0.2]), 0),
 (array([5.1, 3.3, 1.7, 0.5]), 0),
 (array([4.8, 3.4, 1.9, 0.2]), 0),
 (array([5. , 3. , 1.6, 0.2]), 0),
 (array([5. , 3.4, 1.6, 0.4]), 0),
 (array([5.2, 3.5, 1.5, 0.2]), 0),
 (array([5.2, 3.4, 1

In [19]:
dataset = np.hstack((X, y.reshape(-1,1)))
np.random.shuffle(dataset)
X_train, X_test ,Y_train, Y_test = train_test_split(dataset[:,:4], dataset[:,4],test_size=0.2)

In [7]:
model =LogisticRegression()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)

In [8]:
accuracy_score(Y_test, Y_pred)

1.0

In [9]:
joblib.dump(model, 'iris.model')

['iris.model']

In [16]:
model.predict([[1,2,0.5,0.4]])

array([0.])